### ISSUE TITLE
"Town" quest broken

### ISSUE THREAD

**Issue by 2egmcd2** [Pairjax/SQBeyondPublic#555] opened 2020-05-14 02:54 UTC
**Describe the bug**
I cannot accept the "join a town" quest. Everytime I try it says "You must specify a valid value for <quest>!" That is all the info I know. I created a town called "pointalpha" and I have 2 members. Because of this bug I cannot progress in the quests.

**To Reproduce**
1. Go to questbook
2. Click on join a town
3. watch as you cannot accept the quest

**Screenshots**
![Screenshot (132)](https://user-images.githubusercontent.com/65324113/81886871-a701ee80-9552-11ea-80e3-6300f67d109b.png)
![Screenshot (131)](https://user-images.githubusercontent.com/65324113/81886873-a8331b80-9552-11ea-898e-cbb90e3f1aea.png)

**Comment by fin444** [comment] 2020-05-14 03:00
Duplicate of #468

**Closed as completed by fin444** 2020-05-14 03:00 UTC
Labels: bug, duplicate
