### ISSUE TITLE
Ketch class counting slipdrives and torpedoes as inventory

### ISSUE THREAD

**Issue by ConsueTerra** [Pairjax/SQBeyondPublic#587] opened 2020-07-03 09:49 UTC
**Describe the bug**
Slipdrive hoppers and dispensers from torpedoes count as inventory

**To Reproduce**
Build a ketch with 2 slip drives, a cargobay, and a torpedo, ship detection fails

**Expected behavior**
If im correct the expected dropper count should be 0 or 1 not 5

**Comment by ConsueTerra** [comment] 2020-07-03 21:19
Update on this bug, it does indeed seem like slip drives with oak signs do not count as inventory but with any other sign they do, same thing with droppers

**Comment by fin444** [comment] 2020-07-04 17:58
Duplicate of #476

**Closed as completed by fin444** 2020-07-04 17:58 UTC
Labels: bug, duplicate
