### ISSUE TITLE
Cap Ship land randomly unclaims

### ISSUE THREAD

**Issue by HailOVERLORD** [Pairjax/SQBeyondPublic#568] opened 2020-05-27 20:40 UTC
I left my Cap ship next to my base, an when i went back the next day, the land was no longer claimed.

Before you ask:
NO there were not non-wilderness chuncks in the way
YES I did make sure that the land was claimed before I logged off yesterday.

PS: a creeper spawned in the ship and blew part of it up, and I had to wait :P

**Comment by fin444** [comment] 2020-05-27 21:04
Duplicate of #537

**Closed as completed by fin444** 2020-05-27 21:04 UTC
Labels: bug, duplicate
